name: Build & Release WebRankSync

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
        cache: gradle

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Create GitHub Release
      id: release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}

    - name: Upload JAR to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: build/libs/WebRankSync-1.0.jar
        asset_name: WebRankSync-1.0.jar
        asset_content_type: application/java-archive
